### ISSUE TITLE
[151 attempt to index ? (a nil value)] {bakapervert}

### ISSUE THREAD

**Issue by confident-hate** [noaione/shosetsu-extensions#1]
**Effected Extension**
bakapervert

**Describe the bug**
151 attempt to index ? (a nil value)

**To Reproduce**
Click on bakapervert
It will display error.

**Comment by noaione** [comment]
Oh, I somehow didn't get notification for this issue. I'm guessing this is another mobile layout related issue

**Comment by noaione** [comment]
Looks to be fixed by https://github.com/noaione/shosetsu-extensions/commit/ecbedd4da8662449755a96b1aa348bad8e85855a

You can update the extension to 1.2.2 and see if it works

**Comment by confident-hate** [comment]
Yes, fixed now
