### ISSUE TITLE
[SOURCE REQUEST] {lightnovels(dot)live}

### ISSUE THREAD

**Issue by confident-hate** [noaione/shosetsu-extensions#3]
# URL of the site
https://lightnovels.live/ or https://lightnovels.me

## Has search, And what options
yes, baseURL .. "/search/" .. queryContent

## Has Cloudflare protection
Not sure if it has any cloudflare protection

## Addtional notes
I tried to make this extension but not sure why I am unable to get/pase json response from document.

Sharing additional work done for reference.

For Novel Listing use this
```
response = RequestDocument(GET("https://lightnovels.me/api/novel/hot-novel?index=0&limit=20", nil, nil))
response = json.decode(response:text())
return map(response["results"], function(v)
return map(response["results"], function(v)
    return Novel {
        title = v.novel_name,
        link = v.novel_slug,
        imageURL = "https://lightnovels.me" .. v.novel_image
    }
end)
```

For chapter list you need to get novel_id form "script#__NEXT_DATA__" **but I am not able to parse this.**
To get novel_id this code should work but...not working for me
Problematic code:
```
local function parseNovel(novelURL)
    local url = "https://lightnovels.live/novel" .. novelURL
    local doc = RequestDocument(GET(url, nil, nil))
    local response = doc:selectFirst("script#__NEXT_DATA__")
    response = json.decode(response:text())
```
If you can solve above problem then it should work
```
local id = response["props"]["pageProps"]["novelInfo"]["novel_id"]
local chapterurl = "https://lightnovels.me/api/chapters?id=" .. id .. "&index=1&limit=50000"
local chResponse = RequestDocument(GET(chapterurl , nil, nil))
chResponse = json.decode(chResponse:text())
```

**Comment by noaione** [comment]
Looks to be Next.js based, I'll try to make it in following days (or maybe hours from me posting this)

**Comment by confident-hate** [comment]
Not sure why but it not indexing in extension list. I think id parameter is too high in index.json

Can you check why this not displaying in extension list.

**Comment by noaione** [comment]
The dev branch should have it, I think it's just because my auto-generation just didn't work as intended

**Comment by noaione** [comment]
Pushed the fix: https://github.com/noaione/shosetsu-extensions/commit/f7264a15092f7f17d22b5d5a35bca7ea8ac6f4e5

Try to refresh the index list again

**Comment by confident-hate** [comment]
Thanks. working now
