### ISSUE TITLE
[BUG] Reigokai - Isekai Lunatic 

### ISSUE THREAD

**Issue by nachfuellbar** [noaione/shosetsu-extensions#4]
**Effected Extension**
Reigokai - Isekai Lunatic	

**Describe the bug**
In Shosetsu the novel translation
https://isekailunatic.com/this-world-is-a-game/
is shown as "Share this:" which is a string grepped from just above the facebook and x buttons
The page title in the html head of the page is salvagable on this title but no other mention seems to occur
Maybe some fallback like "if i get Share This, use page title instead" would help

**To Reproduce**
1. Go to the extension
2. Click on 'The World is a Game" 
3. After loading the chapters it's already displaying the wrong name

**Expected behavior**
To show the real novel name

**Comment by noaione** [comment]
~~That part should be removed actually, I'll fix it later~~

Edit: I misunderstood the problem, will fix soon

**Comment by noaione** [comment]
Should be fixed by https://github.com/noaione/shosetsu-extensions/commit/8bc13e6ea70e584bfd04ab3b2591cf6084d61588

**Comment by nachfuellbar** [comment]
Looks good to me
Now I see the right title :)
