### ISSUE TITLE
[BUG] Re:Library

### ISSUE THREAD

**Issue by yuukiw** [noaione/shosetsu-extensions#5]
**Effected Extension**
Which extension(s) is effected by this bug

**Describe the bug**
Search works and finds novel but the chapter number is always 0

**To Reproduce**
Steps to any novel of them

**Expected behavior**
it finding chapter

**Additional context**
recently they did a small site update making it a bit more modern. I gues they changed the chapter container or something

**Comment by yuukiw** [comment]
correction it seem to be only specific works for example https://re-library.com/translations/a-silver-dragon-queen-turned-me-into-a-young-dragon-princess/

**Comment by noaione** [comment]
Might be fixed by https://github.com/noaione/shosetsu-extensions/commit/44da9ee7e1aaef53f647db89069ba01eabe2c622

Update to 0.1.11
