### ISSUE TITLE
[BUG] Reigokai

### ISSUE THREAD

**Issue by nachfuellbar** [noaione/shosetsu-extensions#7]
**Effected Extension**
Which extension(s) is effected by this bug

**Describe the bug**
Extension seems to add the base URL in front of the full URL (with missing colon between https and //) to the novel e.g.
https://isekailunatic.comhttps//reigokaitranslations.com......

**To Reproduce**
1. Go to Reigokai Extension and open it
2. Click on any of the novels listed there
3. See error

**Expected behavior**
The novel loads

**Screenshots**
![Screenshot_20241004-154124](https://github.com/user-attachments/assets/c2acf478-1c23-471e-b9f7-480c9de0f3e7)
![Screenshot_20241004-154129](https://github.com/user-attachments/assets/b2850831-122a-4b86-894d-cd2622b3aec5)

**Desktop (please complete the following information):**
 - OS: Android 14
 - Application Version: 2.4.4
 - Extension Version: 0.2.1

**Additional context**
I don't know when it stopped working but in August it still worked for me

**Comment by noaione** [comment]
Looks to be a domain update

**Comment by noaione** [comment]
Please update to 0.3.0
